version: 2

sources:
  - name: staging
    database: dtc-de-course-378220
    schema: trips_data_all

    tables:
      - name: yellow_tripdata_partitioned
      - name: green_tripdata_partitioned